import type {
  Business,
  Transaction,
  Receivable,
  Payable,
  Customer,
  Employee,
  Shift,
  AiAction,
  AiInsight,
  PeerBenchmark,
} from "./types";
import { daysFromToday, hoursFromNow, nowIso } from "./clock";

export const BUSINESS_ID = "biz_demo";

/**
 * Seed business. `name` is the single place a user-typed free-text string lives
 * (the owner names their own business). Everything else that is shown to the
 * user is referenced via i18n keys so there are no hardcoded natural-language
 * strings in the mock data.
 */
export const defaultBusiness: Business = {
  id: BUSINESS_ID,
  name: "Sunrise Noodle House",
  type: "restaurant",
  countryCode: "CN",
  currency: "CNY",
  timezone: "Asia/Shanghai",
  uiLanguage: "zh-CN",
  aiAdvisorLanguage: "zh-CN",
  employeeCountRange: "6-15",
  safetyCashBuffer: 5000,
  demoMode: true,
  createdAt: "2024-01-01T00:00:00Z",
  updatedAt: nowIso(),
};

// --- Transactions (today + recent history) ---
export const mockTransactions: Transaction[] = [
  {
    id: "t1",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 1280,
    currency: "CNY",
    category: "sales",
    descriptionKey: "mock.tx.lunchService",
    paymentMethod: "wallet",
    occurredAt: hoursFromNow(-2),
    source: "pos_import",
    createdAt: hoursFromNow(-2),
    updatedAt: hoursFromNow(-2),
  },
  {
    id: "t2",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 860,
    currency: "CNY",
    category: "sales",
    descriptionKey: "mock.tx.takeaway",
    paymentMethod: "wallet",
    occurredAt: hoursFromNow(-3),
    source: "pos_import",
    createdAt: hoursFromNow(-3),
    updatedAt: hoursFromNow(-3),
  },
  {
    id: "t3",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 540,
    currency: "CNY",
    category: "service",
    descriptionKey: "mock.tx.cateringDeposit",
    paymentMethod: "bank",
    occurredAt: hoursFromNow(-5),
    source: "manual",
    createdAt: hoursFromNow(-5),
    updatedAt: hoursFromNow(-5),
  },
  {
    id: "t4",
    businessId: BUSINESS_ID,
    type: "expense",
    amount: 920,
    currency: "CNY",
    category: "raw_materials",
    descriptionKey: "mock.tx.freshProduce",
    paymentMethod: "cash",
    occurredAt: hoursFromNow(-6),
    source: "receipt",
    createdAt: hoursFromNow(-6),
    updatedAt: hoursFromNow(-6),
  },
  {
    id: "t5",
    businessId: BUSINESS_ID,
    type: "expense",
    amount: 180,
    currency: "CNY",
    category: "utilities",
    descriptionKey: "mock.tx.gasRefill",
    paymentMethod: "card",
    occurredAt: hoursFromNow(-7),
    source: "manual",
    createdAt: hoursFromNow(-7),
    updatedAt: hoursFromNow(-7),
  },
  {
    id: "t6",
    businessId: BUSINESS_ID,
    type: "expense",
    amount: 300,
    currency: "CNY",
    category: "platform_commission",
    descriptionKey: "mock.tx.deliveryFee",
    paymentMethod: "wallet",
    occurredAt: hoursFromNow(-4),
    source: "pos_import",
    createdAt: hoursFromNow(-4),
    updatedAt: hoursFromNow(-4),
  },
  {
    id: "t7",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 2380,
    currency: "CNY",
    category: "sales",
    descriptionKey: "mock.tx.dailySales",
    paymentMethod: "wallet",
    occurredAt: daysFromToday(-1),
    source: "pos_import",
    createdAt: daysFromToday(-1),
    updatedAt: daysFromToday(-1),
  },
  {
    id: "t8",
    businessId: BUSINESS_ID,
    type: "expense",
    amount: 1100,
    currency: "CNY",
    category: "raw_materials",
    descriptionKey: "mock.tx.supplierDelivery",
    paymentMethod: "bank",
    occurredAt: daysFromToday(-1),
    source: "receipt",
    createdAt: daysFromToday(-1),
    updatedAt: daysFromToday(-1),
  },
  {
    id: "t9",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 2650,
    currency: "CNY",
    category: "sales",
    descriptionKey: "mock.tx.dailySales",
    paymentMethod: "wallet",
    occurredAt: daysFromToday(-2),
    source: "pos_import",
    createdAt: daysFromToday(-2),
    updatedAt: daysFromToday(-2),
  },
  {
    id: "t10",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 2210,
    currency: "CNY",
    category: "sales",
    descriptionKey: "mock.tx.dailySales",
    paymentMethod: "wallet",
    occurredAt: daysFromToday(-3),
    source: "pos_import",
    createdAt: daysFromToday(-3),
    updatedAt: daysFromToday(-3),
  },
  {
    id: "t11",
    businessId: BUSINESS_ID,
    type: "income",
    amount: 2900,
    currency: "CNY",
    category: "sales",
    descriptionKey: "mock.tx.weekendSales",
    paymentMethod: "wallet",
    occurredAt: daysFromToday(-4),
    source: "pos_import",
    createdAt: daysFromToday(-4),
    updatedAt: daysFromToday(-4),
  },
  {
    id: "t12",
    businessId: BUSINESS_ID,
    type: "expense",
    amount: 8000,
    currency: "CNY",
    category: "rent",
    descriptionKey: "mock.tx.monthlyRent",
    paymentMethod: "bank",
    occurredAt: daysFromToday(-3),
    source: "manual",
    createdAt: daysFromToday(-3),
    updatedAt: daysFromToday(-3),
  },
];

export const mockReceivables: Receivable[] = [
  {
    id: "r1",
    businessId: BUSINESS_ID,
    customerId: "c1",
    amount: 5600,
    currency: "CNY",
    dueDate: daysFromToday(-3),
    status: "overdue",
    noteKey: "mock.receivable.companyCatering",
    createdAt: daysFromToday(-20),
    updatedAt: daysFromToday(-3),
  },
  {
    id: "r2",
    businessId: BUSINESS_ID,
    customerId: "c2",
    amount: 4000,
    currency: "CNY",
    dueDate: daysFromToday(2),
    status: "open",
    noteKey: "mock.receivable.eventBalance",
    createdAt: daysFromToday(-10),
    updatedAt: daysFromToday(-10),
  },
  {
    id: "r3",
    businessId: BUSINESS_ID,
    customerId: "c3",
    amount: 1800,
    currency: "CNY",
    dueDate: daysFromToday(9),
    status: "open",
    createdAt: daysFromToday(-5),
    updatedAt: daysFromToday(-5),
  },
];

export const mockPayables: Payable[] = [
  {
    id: "p1",
    businessId: BUSINESS_ID,
    vendorId: "v1",
    vendorNameKey: "mock.vendor.meatSupplier",
    amount: 6200,
    currency: "CNY",
    dueDate: daysFromToday(4),
    status: "open",
    noteKey: "mock.payable.meatSupplier",
    createdAt: daysFromToday(-6),
    updatedAt: daysFromToday(-6),
  },
  {
    id: "p2",
    businessId: BUSINESS_ID,
    vendorId: "v2",
    vendorNameKey: "mock.vendor.vegWholesaler",
    amount: 2400,
    currency: "CNY",
    dueDate: daysFromToday(1),
    status: "open",
    noteKey: "mock.payable.vegWholesaler",
    createdAt: daysFromToday(-4),
    updatedAt: daysFromToday(-4),
  },
  {
    id: "p3",
    businessId: BUSINESS_ID,
    vendorId: "v3",
    vendorNameKey: "mock.vendor.payroll",
    amount: 9500,
    currency: "CNY",
    dueDate: daysFromToday(14),
    status: "open",
    isPayroll: true,
    noteKey: "mock.payable.payroll",
    createdAt: daysFromToday(-2),
    updatedAt: daysFromToday(-2),
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    businessId: BUSINESS_ID,
    nameKey: "mock.customer.hongtuTech",
    phone: "+86 138 0000 1111",
    totalSpend: 48600,
    visitCount: 36,
    lastPurchaseAt: daysFromToday(-2),
    riskSegment: "high_value",
  },
  {
    id: "c2",
    businessId: BUSINESS_ID,
    nameKey: "mock.customer.mrWang",
    phone: "+86 139 2222 3333",
    totalSpend: 12400,
    visitCount: 52,
    lastPurchaseAt: daysFromToday(-45),
    riskSegment: "at_risk",
  },
  {
    id: "c3",
    businessId: BUSINESS_ID,
    nameKey: "mock.customer.lilyChen",
    phone: "+86 137 4444 5555",
    totalSpend: 3200,
    visitCount: 18,
    lastPurchaseAt: daysFromToday(-7),
    riskSegment: "price_sensitive",
  },
  {
    id: "c4",
    businessId: BUSINESS_ID,
    nameKey: "mock.customer.zhangFamily",
    phone: "+86 136 6666 7777",
    totalSpend: 980,
    visitCount: 3,
    lastPurchaseAt: daysFromToday(-3),
    riskSegment: "new",
  },
  {
    id: "c5",
    businessId: BUSINESS_ID,
    nameKey: "mock.customer.oldTownOffice",
    phone: "+86 135 8888 9999",
    totalSpend: 21000,
    visitCount: 60,
    lastPurchaseAt: daysFromToday(-90),
    riskSegment: "dormant",
  },
];

export const mockEmployees: Employee[] = [
  {
    id: "e1",
    businessId: BUSINESS_ID,
    nameKey: "mock.employee.chefLiu",
    role: "manager",
    phone: "+86 130 1111 0000",
    hourlyRate: 45,
    consentForGeofencing: true,
    status: "active",
    clockedInToday: true,
  },
  {
    id: "e2",
    businessId: BUSINESS_ID,
    nameKey: "mock.employee.mei",
    role: "employee",
    phone: "+86 131 2222 0000",
    hourlyRate: 28,
    consentForGeofencing: true,
    status: "active",
    clockedInToday: true,
  },
  {
    id: "e3",
    businessId: BUSINESS_ID,
    nameKey: "mock.employee.jun",
    role: "employee",
    phone: "+86 132 3333 0000",
    hourlyRate: 28,
    consentForGeofencing: false,
    status: "active",
    clockedInToday: false,
  },
  {
    id: "e4",
    businessId: BUSINESS_ID,
    nameKey: "mock.employee.auntZhao",
    role: "employee",
    phone: "+86 133 4444 0000",
    hourlyRate: 26,
    consentForGeofencing: true,
    status: "active",
    clockedInToday: true,
  },
  {
    id: "e5",
    businessId: BUSINESS_ID,
    nameKey: "mock.employee.kevin",
    role: "accountant",
    phone: "+86 134 5555 0000",
    hourlyRate: 50,
    consentForGeofencing: false,
    status: "active",
    clockedInToday: false,
  },
];

const DAY_KEYS = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"] as const;
export const SCHEDULE_DAYS = DAY_KEYS;

export const mockShifts: Shift[] = mockEmployees.flatMap((e, i) =>
  DAY_KEYS.slice(0, 5).map((day) => ({
    id: `s_${e.id}_${day}`,
    businessId: BUSINESS_ID,
    employeeId: e.id,
    day,
    startTime: "10:00",
    endTime: i % 2 === 0 ? "18:00" : "22:00",
    status: "scheduled" as const,
  }))
);

export const mockActions: AiAction[] = [
  {
    id: "a1",
    businessId: BUSINESS_ID,
    type: "collect_payment",
    titleKey: "mock.action.collectPayment.title",
    reasonKey: "mock.action.collectPayment.reason",
    draftKey: "mock.action.collectPayment.draft",
    params: { amount: 9600, count: 2 },
    evidenceKeys: ["mock.action.collectPayment.ev1", "mock.action.collectPayment.ev2"],
    status: "draft",
    impactAmount: 9600,
    confidence: "high",
    createdAt: hoursFromNow(-1),
    updatedAt: hoursFromNow(-1),
  },
  {
    id: "a2",
    businessId: BUSINESS_ID,
    type: "customer_winback",
    titleKey: "mock.action.winback.title",
    reasonKey: "mock.action.winback.reason",
    draftKey: "mock.action.winback.draft",
    params: { visits: 52, days: 45 },
    evidenceKeys: ["mock.action.winback.ev1"],
    status: "draft",
    impactAmount: 1200,
    confidence: "medium",
    createdAt: hoursFromNow(-2),
    updatedAt: hoursFromNow(-2),
  },
  {
    id: "a3",
    businessId: BUSINESS_ID,
    type: "delay_payment",
    titleKey: "mock.action.delayPayment.title",
    reasonKey: "mock.action.delayPayment.reason",
    draftKey: "mock.action.delayPayment.draft",
    params: { amount: 2400, days: 3 },
    evidenceKeys: ["mock.action.delayPayment.ev1"],
    status: "draft",
    impactAmount: 2400,
    confidence: "medium",
    createdAt: hoursFromNow(-3),
    updatedAt: hoursFromNow(-3),
  },
];

export const mockInsights: AiInsight[] = [
  {
    id: "i1",
    businessId: BUSINESS_ID,
    type: "cashflow",
    titleKey: "mock.insight.tightCash.title",
    summaryKey: "mock.insight.tightCash.summary",
    evidenceKeys: [
      "mock.insight.tightCash.ev1",
      "mock.insight.tightCash.ev2",
      "mock.insight.tightCash.ev3",
    ],
    impactAmount: 9600,
    confidence: "high",
    recommendedActionType: "collect_payment",
    createdAt: hoursFromNow(-1),
  },
];

export const mockPeerBenchmark: PeerBenchmark = {
  sampleSize: 142,
  grossMarginLow: 0.55,
  grossMarginHigh: 0.68,
  yourMargin: 0.61,
  costStructure: [
    { category: "raw_materials", you: 0.34, peers: 0.32 },
    { category: "payroll", you: 0.22, peers: 0.24 },
    { category: "rent", you: 0.14, peers: 0.12 },
    { category: "marketing", you: 0.03, peers: 0.05 },
  ],
  groupBuying: [
    { id: "gb1", titleKey: "mock.network.groupBuy.oil", participants: 18 },
    { id: "gb2", titleKey: "mock.network.groupBuy.coldChain", participants: 9 },
  ],
};

export const seed = {
  transactions: mockTransactions,
  receivables: mockReceivables,
  payables: mockPayables,
  customers: mockCustomers,
  employees: mockEmployees,
  shifts: mockShifts,
  actions: mockActions,
  insights: mockInsights,
};
